from __future__ import annotations

from dataclasses import dataclass

from rewards.transition_metrics import (
    TransitionMetrics,
)


class RewardV1Error(ValueError):
    pass


@dataclass(frozen=True)
class RewardV1Weights:
    step: float = 1.0
    tet_growth: float = 1.0
    revert: float = 0.10

    convergence_loss: float = 1.0
    convergence_recovery: float = 1.0

    terminal_success: float = 3.0
    terminal_failure: float = 3.0


DEFAULT_REWARD_V1_WEIGHTS = (
    RewardV1Weights()
)


@dataclass(frozen=True)
class RewardV1Breakdown:
    step: float
    tet_growth: float
    revert: float
    convergence: float
    terminal: float
    total: float


def compute_reward_v1(
    *,
    metrics: TransitionMetrics,
    initial_actionable_count: int,
    weights: RewardV1Weights = (
        DEFAULT_REWARD_V1_WEIGHTS
    ),
) -> RewardV1Breakdown:
    """
    Selection Reward V1.

    This reward describes Stage-2 loop selection only.

    It deliberately excludes:
        - commit bonus;
        - vertex growth;
        - runtime;
        - mm_polys;
        - available_drop;
        - nonmanifold/high-genus/buggy-chain diagnostics;
        - FINALIZE/full-hex outcome.

    Those quantities remain available for observation/evaluation.
    """

    initial_actionable_count = int(
        initial_actionable_count
    )

    if initial_actionable_count <= 0:
        raise RewardV1Error(
            "initial_actionable_count "
            "must be positive"
        )

    # ------------------------------------------------------------
    # Normalized action-count cost.
    # ------------------------------------------------------------

    step_component = (
        - weights.step
        /
        initial_actionable_count
    )

    # ------------------------------------------------------------
    # Persistent volumetric-complexity growth.
    #
    # The sum over an episode telescopes:
    #
    #   sum log(T_after / T_before)
    #       = log(T_final / T_initial)
    # ------------------------------------------------------------

    tet_component = (
        - weights.tet_growth
        *
        float(
            metrics.log_tet_growth
        )
    )

    # ------------------------------------------------------------
    # Reverted cuts are independently undesirable because LoopyCuts
    # does not rollback the tessellation generated by a failed cut.
    # ------------------------------------------------------------

    revert_component = (
        - weights.revert
        *
        int(
            metrics.reverted
        )
    )

    # ------------------------------------------------------------
    # Convergence semantics.
    #
    # First convergence itself receives no direct bonus.
    #
    # Losing an already reached convergence is penalized.
    # A later recovery receives the symmetric positive term.
    # ------------------------------------------------------------

    convergence_component = 0.0

    if (
        int(
            metrics.convergence_delta
        )
        ==
        -1
    ):
        convergence_component = (
            - weights.convergence_loss
        )

    elif (
        int(
            metrics.convergence_delta
        )
        ==
        1
        and
        not int(
            metrics.first_convergence
        )
    ):
        convergence_component = (
            weights.convergence_recovery
        )

    # ------------------------------------------------------------
    # Terminal Stage-2 selection outcome.
    # ------------------------------------------------------------

    terminal_component = 0.0

    if int(
        metrics.selection_success
    ):
        terminal_component += (
            weights.terminal_success
        )

    if int(
        metrics.terminal_failure
    ):
        terminal_component -= (
            weights.terminal_failure
        )

    total = (
        step_component
        +
        tet_component
        +
        revert_component
        +
        convergence_component
        +
        terminal_component
    )

    return RewardV1Breakdown(
        step=float(
            step_component
        ),

        tet_growth=float(
            tet_component
        ),

        revert=float(
            revert_component
        ),

        convergence=float(
            convergence_component
        ),

        terminal=float(
            terminal_component
        ),

        total=float(
            total
        ),
    )
